import { RULE_SYSTEMS } from "./ruleSystems.js";
import { TAG_CATEGORIES } from "./abilityKinds.js";

/**
 * ICON core tags (campaignId: null). Doc id = key.
 * Summaries are paraphrases for VTT tooling — not full copyrighted rules text.
 */
export const ICON_TAGS_SEED = Object.freeze([
    {
        key: "pierce",
        label: "Pierce",
        category: TAG_CATEGORIES.ATTACK,
        summary: "El ataque atraviesa Armor.",
        aliases: ["Piercing"],
    },
    {
        key: "true-strike",
        label: "True Strike",
        category: TAG_CATEGORIES.ATTACK,
        summary: "Ignora Cover y Evasion al resolver el ataque.",
        aliases: ["TrueStrike"],
    },
    {
        key: "divine",
        label: "Divine",
        category: TAG_CATEGORIES.ATTACK,
        summary: "Daño divino — bypass de ciertas resistencias según la ficha.",
        aliases: [],
    },
    {
        key: "fray",
        label: "Fray",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Daño plano de Fray (suele aplicar en hit y miss de ataques).",
        aliases: [],
    },
    {
        key: "armor",
        label: "Armor",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Mitigación plana de daño entrante.",
        aliases: [],
    },
    {
        key: "rush",
        label: "Rush",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Movimiento Rush: unstoppable e inmune a daño durante el move.",
        aliases: [],
    },
    {
        key: "shove",
        label: "Shove",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Empuje involuntario en línea recta; puede causar Collide.",
        aliases: [],
    },
    {
        key: "collide",
        label: "Collide",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Trigger al chocar con personaje, objeto o elevación mayor.",
        aliases: [],
    },
    {
        key: "combo",
        label: "Combo",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Otorga o gasta token Combo para líneas mejoradas.",
        aliases: [],
    },
    {
        key: "mark",
        label: "Mark",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Marca un objetivo (uno por habilidad / par).",
        aliases: [],
    },
    {
        key: "aura",
        label: "Aura",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Área continua desde el origen mientras se mantenga.",
        aliases: [],
    },
    {
        key: "stance",
        label: "Stance",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Stance positiva; normalmente una a la vez.",
        aliases: [],
    },
    {
        key: "charge",
        label: "Charge",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Trigger Charge (una vez por uso de habilidad salvo texto).",
        aliases: [],
    },
    {
        key: "heroic",
        label: "Heroic",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Trigger de familia Stalwart.",
        aliases: [],
    },
    {
        key: "finishing-blow",
        label: "Finishing Blow",
        category: TAG_CATEGORIES.EFFECT,
        summary: "Trigger Vagabond vs objetivos bloodied.",
        aliases: ["FinishingBlow"],
    },
    {
        key: "slashed",
        label: "Slashed",
        category: TAG_CATEGORIES.STATUS,
        summary: "Daño al moverse (cap por turno).",
        aliases: [],
    },
    {
        key: "weakened",
        label: "Weakened",
        category: TAG_CATEGORIES.STATUS,
        summary: "Inflige menos daño.",
        aliases: [],
    },
    {
        key: "stunned",
        label: "Stunned",
        category: TAG_CATEGORIES.STATUS,
        summary: "Limita interrupts; la siguiente habilidad termina el turno y limpia.",
        aliases: [],
    },
    {
        key: "sealed",
        label: "Sealed",
        category: TAG_CATEGORIES.STATUS,
        summary: "No puede infligir statuses.",
        aliases: [],
    },
    {
        key: "pacified",
        label: "Pacified",
        category: TAG_CATEGORIES.STATUS,
        summary: "Daño a la mitad; se rompe al recibir daño de un foe.",
        aliases: [],
    },
    {
        key: "blinded",
        label: "Blinded",
        category: TAG_CATEGORIES.STATUS,
        summary: "Rango de ataque limitado.",
        aliases: ["Blind", "Cegado"],
    },
    {
        key: "dazed",
        label: "Dazed",
        category: TAG_CATEGORIES.STATUS,
        summary: "Curse en ataques.",
        aliases: [],
    },
    {
        key: "shattered",
        label: "Shattered",
        category: TAG_CATEGORIES.STATUS,
        summary: "No puede ganar ni beneficiarse de Vigor.",
        aliases: [],
    },
    {
        key: "vulnerable",
        label: "Vulnerable",
        category: TAG_CATEGORIES.STATUS,
        summary: "+1 daño por instancia recibida.",
        aliases: [],
    },
    {
        key: "counter",
        label: "Counter",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Tag positivo de contraataque / respuesta.",
        aliases: [],
    },
    {
        key: "dodge",
        label: "Dodge",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Tag positivo de esquiva.",
        aliases: [],
    },
    {
        key: "evasion",
        label: "Evasion",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Tag positivo de evasión.",
        aliases: [],
    },
    {
        key: "flying",
        label: "Flying",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Vuelo / elevación.",
        aliases: [],
    },
    {
        key: "defiance",
        label: "Defiance",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Tag positivo de resistencia a ciertos efectos.",
        aliases: [],
    },
    {
        key: "regeneration",
        label: "Regeneration",
        category: TAG_CATEGORIES.TRAIT,
        summary: "Recuperación de VIT / HP según la ficha.",
        aliases: [],
    },
].map((t) => ({
    ...t,
    rulesSystem: RULE_SYSTEMS.ICON,
    campaignId: null,
    description: t.summary,
    effects: [],
})));
